<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Novolis.Messaging.Channels.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.Testing.TestBases" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\src\Novolis.Messaging.Channels\Novolis.Messaging.Channels.csproj" />
    
  </ItemGroup>
</Project>
