<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Novolis.Messaging.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\src\Novolis.Messaging\Novolis.Messaging.csproj" />
    <ProjectReference Include="..\..\..\novolis-testing\src\Novolis.Testing.TestBases\Novolis.Testing.TestBases.csproj" />
    <ProjectReference Include="..\..\..\novolis-testing\src\Novolis.Testing.TUnit\Novolis.Testing.TUnit.csproj" />
  </ItemGroup>
</Project>
